spring:
  application:
    name: eureka-service

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    order:
      path: /orders/**
      serviceId: order-service
    product:
      path: /products/**
      serviceId: product-service
    user:
      path: /users/**
      serviceId: user-service
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

ribbon:
  ReadTimeout: 60000
  ConnectionTimeout: 3000
